# Generated by Django 3.0.8 on 2020-07-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_editor_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='timestamp',
            new_name='pub_date',
        ),
    ]
